Merge worldcrafter
MaxNeedsSnacks/Interactio pull request #42
Opened 2021-04-02 04:24 UTC by murapix

Huge changes all around here:
* Recipe functionality is nearly all condensed into the base `InWorldRecipe` class
* An event system's been added in
* All output types are merged into a single `DynamicOutput` with per-recipe output type blacklists
  * As such, duplicate recipes such as `ItemFluidTransform` and `FluidFluidTransform` have been merged into single types
* Fluid recipes now can have a duration and may require multiple fluid source blocks
* Recipes for item burning, lightning striking a block, killing an entity while it's standing on specific blocks/items
* and a few more, more minor changes

Some things still left to do in future efforts:
* Refactor JEI support to be dynamically constructed based on recipe components
* Add JEI support for all recipe types
* Add various events to the recipe Event system, including those from the Issues list
* Updating the docs to reflect the new changes

2021-04-02 14:47 UTC, MaxNeedsSnacks commented
Hey, there it is, nice! Thanks for the pull request, I'll try to put together a full review soon so we can see if stuff needs changing, but from a cursory glance, I really liked the direction you took with this!

2021-04-02 15:10 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/integration/jei/InteractioJEIPlugin.java
> +    public static void setOutputLists(IIngredients ingredients, DynamicOutput output) {
I kind of want to stop using streams here (and in other possibly performance critical sections) as they *do* produce a fair amount of overhead. Maybe later down the line in another release we can replace the stream-related calls (`map`, `fitler`, etc.) with utility methods that just iterate over the collection

2021-04-02 15:11 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/integration/jei/categories/BlockAnvilSmashingCategory.java
> +        ingredients.setInputs(VanillaTypes.ITEM, recipe.getBlockInput().getMatching()
Same thing as above goes for this (and the other recipe categories as well), but it's not exactly a high-priority issue so don't worry about it too much for now

2021-04-02 15:21 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/BlockAnvilSmashingRecipe.java
> +        this.postCraft.add((hitPos, info) -> {
Would it be possible to just migrate this to an event players could specify in JSON rather than applying it by default? If so, we could just get rid of the damage parameter and make it part of the event's parameters instead, streamlining JSON structure a fair bit

2021-04-02 15:26 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/ItemAnvilSmashingRecipe.java
> +        this.keepCraftingConditions.add((entities, info) -> {
Similarly to the block anvil damage event, I wanna see whether we can migrate this to an event specific to this recipe type. Optimally, we'd wanna merge them into one condition obviously, but that probably won't be possible here considering the different use cases and more importantly, parameter types

2021-04-02 15:38 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/ItemFluidRecipe.java
> +        this.onCraftEnd.add((items, info) -> {
Same thing as with the anvil recipes, could we try to generify this into an event somehow so we can get rid of the `consumeFluid` double entirely?

2021-04-02 15:40 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/ItemLightningRecipe.java
> +        this.postCraft.add((entities, info) -> sendParticle(ParticleTypes.END_ROD, info.getWorld(), Vec3.atCenterOf(info.getPos())));
This could probably be replaced with the pre-registered particle event?

2021-04-02 15:42 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/base/InWorldRecipe.java
> +            Stream<ResourceLocation> locs = Streams.stream(array.iterator())
As with everything, we should look into whether de-streamifying this is a good idea or not (i.e. whether the overhead caused by streams is critical here or not)

2021-04-02 15:44 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/base/InWorldRecipe.java
> +        return true;
We might be fine setting this to false since I remember @LatvianModder saying something about KubeJS skipping special recipes during (de)serialisation, which might break with people trying to create in-world recipes in KubeJS

2021-04-02 15:45 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/duration/DurationManager.java
> +            Interactio.LOGGER.warn("|><|" + duration + "|><|" + input + "|><|" + state);
This should be moved to debug or commented out for a production release

2021-04-02 15:46 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/base/InWorldRecipeType.java
> +    public static final InWorldRecipeType<ItemFluidRecipe> ITEM_FLUID = create("item_fluid_transform", ItemFluidRecipe.SERIALIZER);
This can probably just be `item_fluid` or some other simpler key. Since this is a major release, I'm not really worried about breaking JSON syntax ^^

2021-04-02 15:49 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/ingredient/EntityIngredient.java
> +//        } else if (json.has("tag")) {
What were the problems with this during implementation?

2021-04-02 15:51 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/BlockAnvilSmashingRecipe.java
> +        this.postCraft.add((hitPos, info) -> {
Ah yeah, we could move this into an event without too much trouble

2021-04-02 15:52 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/ItemAnvilSmashingRecipe.java
> +        this.keepCraftingConditions.add((entities, info) -> {
I can try to merge these, but yeah, different parameter types makes that iffy

2021-04-02 15:53 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/ItemLightningRecipe.java
> +        this.postCraft.add((entities, info) -> sendParticle(ParticleTypes.END_ROD, info.getWorld(), Vec3.atCenterOf(info.getPos())));
Oh right, this was one of the earlier ones, that should be switched over the pre-registered event

2021-04-02 15:53 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/util/CraftingInfo.java
> +    public abstract BlockPos getPos();
We could move this to `Vec3` to allow for additional detail in events that use position (`DefaultInfo` would then just return the vector at the center of the block it's targetting)

2021-04-02 15:53 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/duration/DurationManager.java
> +            Interactio.LOGGER.warn("|><|" + duration + "|><|" + input + "|><|" + state);
Woops, will do

2021-04-02 15:54 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/util/IEntrySerializer.java
> +            return Optional.ofNullable(ForgeRegistries.ENTITIES.getValue(id))
Might want to move this to `architectury` registries down the line

2021-04-02 15:55 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/ingredient/EntityIngredient.java
> +//        } else if (json.has("tag")) {
I'm guessing you mean the tag section that's commented out? I just wasn't able to find any tag registry or anything to pull from for those.

2021-04-02 15:59 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/integration/jei/InteractioJEIPlugin.java
> +    public static void setOutputLists(IIngredients ingredients, DynamicOutput output) {
Streams here in JEI I wouldn't worry about - especially since these here are called once when the recipe is loaded in, and the data's stored for any future lookups. In other sections though, I've just had bad past experience with pre-optimization (my *own* pre-optimization), so I would rather do some performance profiling first, just to see if there's any actual issues.

2021-04-02 16:00 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/util/CraftingInfo.java
> +    public abstract BlockPos getPos();
Yeah, that shouldn't be a problem

2021-04-02 16:02 UTC, MaxNeedsSnacks approved these changes
Looks good to me overall!

Before merging, I'd still like to see whether we can address some of the things I've noted along the way, and I want to do some overall code cleanup and futureproofing before the actual public release, but generally this *should* be good to go!

2021-04-02 16:06 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/integration/jei/InteractioJEIPlugin.java
> +    public static void setOutputLists(IIngredients ingredients, DynamicOutput output) {
Ah that's fair! I was kind of worried these would be called every time the recipe display is initialised when scrolling through recipe pages, but this should (hopefully) be fine then!

2021-04-02 16:07 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/ingredient/EntityIngredient.java
> +//        } else if (json.has("tag")) {
Ah that should be `EntityTypeTags` I think

2021-04-03 23:44 UTC, MaxNeedsSnacks requested changes
Going into nitpick territory now, so this should be pretty much good to go!

2021-04-03 23:44 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +        events.put(new ResourceLocation("consumeFluids"), (inputs, info, json) -> {
Very tiny nitpick: ResourceLocations in Minecraft should generally use snake_case rather than camelCase

2021-04-03 23:44 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +            double consumeFluid = Utils.parseChance(json, "consumeFluid");
We can rename this to "chance" since we've already established what this is a chance for.

2021-04-03 23:44 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +        events.put(new ResourceLocation("breakAnvil"), (inputs, info, json) -> {
Same as above, plus I think "damage_anvil" seems like a better fit here

2021-04-03 23:44 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +            double damage = Utils.getDouble(json, "damage");
Same as above, renaming to "chance" might look better if we end up going with "damage_anvil"

2021-04-03 23:45 UTC, MaxNeedsSnacks commented
Maybe as a general question to cast into the room: We should probably decide on a uniform format for JSON keys (either snake_case or camelCase), so what do you think would fit better?

2021-04-03 23:47 UTC, MaxNeedsSnacks commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +        events.put(new ResourceLocation("consumeFluids"), (inputs, info, json) -> {
Actually turns out this is not a nitpick at all: ResLocs **only** accept lowercase latters, so this will in fact crash in production

2021-04-04 01:28 UTC, murapix commented on src/main/java/ky/someone/mods/interactio/recipe/Events.java
> +        events.put(new ResourceLocation("consumeFluids"), (inputs, info, json) -> {
ugh, right, I keep forgetting that's a rule, stupid nonsense restrictions... (I know why it's a thing, still stupid though)

2021-04-04 01:31 UTC, murapix commented
I'm personally just more of a fan of camelCase, although that does kinda come with the territory of being a programmer these days

2021-04-04 01:46 UTC, MaxNeedsSnacks approved these changes

2021-04-04 15:00 UTC, MaxNeedsSnacks commented
I'll be moving this to last call so that if anyone (most likely you or me) still has any changes to suggest, they can do so until Tuesday ^^

2021-04-07 16:14 UTC, merged

2021-04-07 16:25 UTC, MaxNeedsSnacks commented
Just refactored and merged this! Just out of interest: Do you happen to have example json recipes I can put on the wiki while I'm re-reworking it later on?

2021-04-07 19:10 UTC, murapix commented
Not exactly example recipes, but here's all the recipes I made to test the changes.
[jeff.zip](https://github.com/MaxNeedsSnacks/Interactio/files/6273947/jeff.zip)